// Package catalogjs renders the MCP operation registry into the browser-ESM
// catalog that cloud mode's in-tab MCP responder serves
// (web/cloud/js/mcp-catalog.generated.js).
//
// The rendering lives here rather than in cmd/genmcpcatalog so the drift guard
// (drift_test.go) can re-run Generate in memory and byte-compare it against the
// checked-in file. See docs/plans/20260710-cloud-mcp-catalog-codegen.md.
package catalogjs

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/korjavin/medicationtrackerbot/internal/mcp/registry"
)

// Exclusion records a registry operation deliberately kept out of the cloud
// catalog. Mirrors internal/server/mcp_coverage_exempt.go: every entry carries
// a Reason, so an omission is always a decision and never an accident.
type Exclusion struct {
	ID     string `json:"id"`
	Reason string `json:"reason"`
}

const gamificationReason = "gamification is deferred project-wide; clamped out of apishim.js PORTED_SET"

// Excluded lists ops per-id (not per-topic) so renaming an op breaks
// TestCloudCatalog_ExclusionsAreRealOps instead of silently excluding nothing.
var Excluded = []Exclusion{
	{ID: "gamification.gauges", Reason: gamificationReason},
	{ID: "gamification.insights", Reason: gamificationReason},
	{ID: "gamification.journey", Reason: gamificationReason},
	{ID: "gamification.rings", Reason: gamificationReason},
	{ID: "gamification.summary", Reason: gamificationReason},
	{ID: "gamification.targets.read", Reason: gamificationReason},
	{ID: "gamification.targets.set", Reason: gamificationReason},
	{ID: "gamification.weekly_review", Reason: gamificationReason},
}

// ExcludedIDs returns id → reason for cheap lookup.
func ExcludedIDs() map[string]string {
	m := make(map[string]string, len(Excluded))
	for _, e := range Excluded {
		m[e.ID] = e.Reason
	}
	return m
}

// entry is the per-operation shape emitted into CATALOG.
type entry struct {
	ID              string          `json:"id"`
	Topic           string          `json:"topic"`
	Method          string          `json:"method"`
	Path            string          `json:"path"`
	PathParams      []string        `json:"path_params,omitempty"`
	Risk            registry.Risk   `json:"risk"`
	Description     string          `json:"description"`
	ResponseSummary string          `json:"response_summary"`
	Required        []string        `json:"required,omitempty"`
	ParamsSchema    json.RawMessage `json:"params_schema,omitempty"`
	BodySchema      json.RawMessage `json:"body_schema,omitempty"`
	ResponseExample string          `json:"response_example,omitempty"`
}

const header = `// Code generated by cmd/genmcpcatalog. DO NOT EDIT.
// Source: internal/mcp/registry.DefaultOperations(). Regenerate: go run ./cmd/genmcpcatalog
// See docs/plans/20260710-cloud-mcp-catalog-codegen.md
`

// Generate renders ops (minus Excluded, sorted by id) as a dependency-free
// browser ESM module exporting CATALOG and EXCLUDED. JSON is valid JS, so the
// entries are emitted as marshalled JSON rather than hand-quoted literals.
func Generate(ops []*registry.Operation) ([]byte, error) {
	excluded := ExcludedIDs()
	entries := make([]entry, 0, len(ops))
	for _, op := range ops {
		if _, skip := excluded[op.ID]; skip {
			continue
		}
		// Reuse the registry's own derivation so the required-field logic
		// cannot drift between bot mode and cloud mode.
		required := registry.MarshalForHelpCompact([]*registry.Operation{op})[0].Required
		entries = append(entries, entry{
			ID:              op.ID,
			Topic:           op.Topic,
			Method:          op.Method,
			Path:            op.Path,
			PathParams:      op.PathParams,
			Risk:            op.Risk,
			Description:     op.Description,
			ResponseSummary: op.ResponseSummary,
			Required:        required,
			ParamsSchema:    op.ParamsSchema,
			BodySchema:      op.BodySchema,
			ResponseExample: op.ResponseExample,
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })

	catalog, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal catalog: %w", err)
	}
	exclusions, err := json.MarshalIndent(Excluded, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal exclusions: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\nexport const CATALOG = ")
	buf.Write(catalog)
	buf.WriteString(";\n\nexport const EXCLUDED = ")
	buf.Write(exclusions)
	buf.WriteString(";\n")
	return buf.Bytes(), nil
}
