// Package medication owns the medications, intake_log, intake_reminders, and
// medication_restocks tables: the user's medication list (CRUD, archival,
// supplements, inventory tracking), scheduled and manual intake events
// (pending / taken / skipped / snoozed / tz_step pre-materialized), reminder
// message-id tracking, and the restock event log.
//
// Repo is the per-domain repository. Construct via store.New / store.NewWithDB
// and reach it as r.Medication; new code should depend on *medication.Repo (or
// a narrow interface satisfied by it) directly.
//
// The 41 methods here form four sibling groups that share the same
// transactional context and the medications.id foreign key, which is why they
// sit in one package:
//   - Medication CRUD (Create / Get / List / Update / Delete plus supplement
//     and creation-time tweaks).
//   - Inventory + restock (DecrementInventory / IncrementInventory /
//     SetInventory / CreateRestock / ListRestocks plus low-stock policy).
//   - Intake log (CreateIntake / CreateManualIntake / ConfirmIntake / Skip /
//     Snooze / Update / Delete / various Get readers / BatchGet /
//     ConfirmIntakesBySchedule).
//   - Intake reminders (CreateIntakeReminder, ListIntakeReminders, batch reader).
//
// Dose-time columns convention (mirrors the top-of-store.go comment): the
// intake_log columns scheduled_at_unix, taken_at_unix, snoozed_until_unix are
// INTEGER unix-seconds-UTC. Writers normalize via t.UTC().Unix(); readers scan
// into int64 / sql.NullInt64 and return time.Unix(n, 0).UTC(). The
// architecture test TestIntakeLogTimeColumnsAreInteger (now in this package's
// time_columns_test.go) fails CI if a future migration regresses any of these
// columns to DATETIME / TEXT.
package medication

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	storedb "github.com/korjavin/medicationtrackerbot/internal/store/db"
)

// ScheduleConfig is the parsed form of Medication.Schedule. The Schedule
// column itself is either a legacy "HH:MM" string (treated as daily with one
// dose) or a JSON document conforming to this struct.
type ScheduleConfig struct {
	Type  string   `json:"type"`            // "daily", "weekly", "as_needed"
	Days  []int    `json:"days,omitempty"`  // 0=Sunday, 1=Monday...
	Times []string `json:"times,omitempty"` // ["08:00", "20:00"]
}

// Medication is one row in the medications table.
type Medication struct {
	ID             int64      `json:"id"`
	Name           string     `json:"name"`
	Dosage         string     `json:"dosage"`
	Schedule       string     `json:"schedule"` // e.g. "09:00" or JSON
	Archived       bool       `json:"archived"`
	Supplement     bool       `json:"supplement"`
	StartDate      *time.Time `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	LastTakenAt    *time.Time `json:"last_taken_at"`
	CreatedAt      time.Time  `json:"created_at"`
	RxCUI          string     `json:"rxcui,omitempty"`
	NormalizedName string     `json:"normalized_name,omitempty"`
	InventoryCount *int       `json:"inventory_count,omitempty"` // NULL = not tracking
	TZShiftPolicy  string     `json:"tz_shift_policy"`           // flexible / medium / strict
}

// ValidSchedule parses the Schedule column into a ScheduleConfig. Legacy
// "HH:MM" strings are accepted as daily with one dose.
func (m *Medication) ValidSchedule() (*ScheduleConfig, error) {
	var s ScheduleConfig
	// Check if legacy "HH:MM"
	if len(m.Schedule) == 5 && m.Schedule[2] == ':' {
		s.Type = "daily"
		s.Times = []string{m.Schedule}
		return &s, nil
	}
	// Try JSON
	if err := json.Unmarshal([]byte(m.Schedule), &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// Restock is one row in the medication_restocks table.
type Restock struct {
	ID           int64     `json:"id"`
	MedicationID int64     `json:"medication_id"`
	Quantity     int       `json:"quantity"`
	Note         string    `json:"note,omitempty"`
	RestockedAt  time.Time `json:"restocked_at"`
}

// IntakeLog is one row in the intake_log table.
//
// Source defaults to "schedule" — the normal autogenerated path. Track D
// of the scheduling-simplification plan adds the "tz_step" source (plan
// steps pre-materialized into intake_log via TZPlanID + TZStepNumber); see
// docs/plans/20260508-simplify-medication-scheduling-utc-and-pre-materialized-steps.md.
type IntakeLog struct {
	ID           int64      `json:"id"`
	MedicationID int64      `json:"medication_id"`
	UserID       int64      `json:"user_id"`
	ScheduledAt  time.Time  `json:"scheduled_at"`
	TakenAt      *time.Time `json:"taken_at,omitempty"`
	Status       string     `json:"status"` // PENDING, TAKEN, SKIPPED, MISSED
	SnoozedUntil *time.Time `json:"snoozed_until,omitempty"`
	Source       string     `json:"source"`                   // "schedule" (default) | "tz_step"
	TZPlanID     *int64     `json:"tz_plan_id,omitempty"`     // set when source='tz_step'
	TZStepNumber *int64     `json:"tz_step_number,omitempty"` // set when source='tz_step'
}

// MedicationSchedule represents a combination of medication ID and target time
// for batch fetching intakes.
type MedicationSchedule struct {
	MedID       int64
	ScheduledAt time.Time
}

// IntakeWithMedication is an intake_log row joined with its parent
// medications row's name + dosage; used by the download endpoints.
type IntakeWithMedication struct {
	IntakeLog
	MedicationName   string `json:"medication_name"`
	MedicationDosage string `json:"medication_dosage"`
}

// Repo is the medication + intake_log + restock + inventory repository.
// Construct with New; share one *Repo per process — the underlying *db.DB
// owns its own connection pool.
type Repo struct {
	db *storedb.DB
}

// New returns a Repo bound to the shared *db.DB. The composition root passes
// in the same *db.DB it gives every other repo so all reads/writes go through
// one connection pool.
func New(d *storedb.DB) *Repo {
	return &Repo{db: d}
}

// -- Medications CRUD --

func (r *Repo) Create(name, dosage, schedule string, startDate, endDate *time.Time, rxcui, normalizedName string, tzShiftPolicy string) (int64, error) {
	if tzShiftPolicy == "" {
		tzShiftPolicy = "flexible"
	}
	res, err := r.db.Exec("INSERT INTO medications (name, dosage, schedule, start_date, end_date, rxcui, normalized_name, tz_shift_policy) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
		name, dosage, schedule, startDate, endDate, rxcui, normalizedName, tzShiftPolicy)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

func (r *Repo) List(showArchived bool) ([]Medication, error) {
	query := `
		SELECT
			m.id, m.name, m.dosage, m.schedule, m.archived, m.supplement, m.start_date, m.end_date, m.created_at, m.rxcui, m.normalized_name, m.inventory_count, m.tz_shift_policy,
			MAX(CASE WHEN l.status = 'TAKEN' THEN l.taken_at_unix ELSE NULL END) as last_taken_unix
		FROM medications m
		LEFT JOIN intake_log l ON m.id = l.medication_id
	`
	if !showArchived {
		query += " WHERE m.archived = 0"
	}
	query += " GROUP BY m.id ORDER BY m.name ASC"

	rows, err := r.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	meds := []Medication{}
	for rows.Next() {
		var m Medication
		var lastTakenUnix sql.NullInt64
		var rxcui, normalizedName sql.NullString
		var inventoryCount sql.NullInt64

		if err := rows.Scan(&m.ID, &m.Name, &m.Dosage, &m.Schedule, &m.Archived, &m.Supplement, &m.StartDate, &m.EndDate, &m.CreatedAt, &rxcui, &normalizedName, &inventoryCount, &m.TZShiftPolicy, &lastTakenUnix); err != nil {
			return nil, err
		}

		if rxcui.Valid {
			m.RxCUI = rxcui.String
		}
		if normalizedName.Valid {
			m.NormalizedName = normalizedName.String
		}
		if inventoryCount.Valid {
			ic := int(inventoryCount.Int64)
			m.InventoryCount = &ic
		}

		if lastTakenUnix.Valid {
			t := time.Unix(lastTakenUnix.Int64, 0).UTC()
			m.LastTakenAt = &t
		}

		meds = append(meds, m)
	}
	return meds, nil
}

func (r *Repo) Get(id int64) (*Medication, error) {
	var m Medication
	var rxcui, normalizedName sql.NullString
	var inventoryCount sql.NullInt64
	err := r.db.QueryRow("SELECT id, name, dosage, schedule, archived, supplement, start_date, end_date, created_at, rxcui, normalized_name, inventory_count, tz_shift_policy FROM medications WHERE id = ?", id).Scan(
		&m.ID, &m.Name, &m.Dosage, &m.Schedule, &m.Archived, &m.Supplement, &m.StartDate, &m.EndDate, &m.CreatedAt, &rxcui, &normalizedName, &inventoryCount, &m.TZShiftPolicy,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	if rxcui.Valid {
		m.RxCUI = rxcui.String
	}
	if normalizedName.Valid {
		m.NormalizedName = normalizedName.String
	}
	if inventoryCount.Valid {
		ic := int(inventoryCount.Int64)
		m.InventoryCount = &ic
	}

	return &m, nil
}

func (r *Repo) Update(id int64, name, dosage, schedule string, archived bool, startDate, endDate *time.Time, rxcui, normalizedName string, inventoryCount *int, tzShiftPolicy string) error {
	if tzShiftPolicy == "" {
		tzShiftPolicy = "flexible"
	}
	_, err := r.db.Exec("UPDATE medications SET name = ?, dosage = ?, schedule = ?, archived = ?, start_date = ?, end_date = ?, rxcui = ?, normalized_name = ?, inventory_count = ?, tz_shift_policy = ? WHERE id = ?",
		name, dosage, schedule, archived, startDate, endDate, rxcui, normalizedName, inventoryCount, tzShiftPolicy, id)
	return err
}

func (r *Repo) Delete(id int64) error {
	_, err := r.db.Exec("DELETE FROM medications WHERE id = ?", id)
	return err
}

func (r *Repo) CanDelete(id int64) (bool, error) {
	var count int
	err := r.db.QueryRow("SELECT COUNT(*) FROM intake_log WHERE medication_id = ?", id).Scan(&count)
	if err != nil {
		return false, err
	}
	return count == 0, nil
}

func (r *Repo) SetSupplement(id int64, supplement bool) error {
	_, err := r.db.Exec("UPDATE medications SET supplement = ? WHERE id = ?", supplement, id)
	return err
}

func (r *Repo) UpdateCreatedAt(id int64, createdAt time.Time) error {
	_, err := r.db.Exec("UPDATE medications SET created_at = ? WHERE id = ?", createdAt, id)
	if err != nil {
		return err
	}
	return nil
}

// -- Inventory Functions --

// DecrementInventory reduces the inventory count by the given quantity.
// Only decrements if inventory is being tracked (not NULL).
func (r *Repo) DecrementInventory(medID int64, qty int) error {
	_, err := r.db.Exec("UPDATE medications SET inventory_count = inventory_count - ? WHERE id = ? AND inventory_count IS NOT NULL", qty, medID)
	return err
}

// IncrementInventory increases the inventory count by the given quantity.
// Only increments if inventory is being tracked (not NULL).
func (r *Repo) IncrementInventory(medID int64, qty int) error {
	_, err := r.db.Exec("UPDATE medications SET inventory_count = inventory_count + ? WHERE id = ? AND inventory_count IS NOT NULL", qty, medID)
	return err
}

// SetInventory sets the inventory count for a medication (nil to disable tracking).
func (r *Repo) SetInventory(medID int64, count *int) error {
	_, err := r.db.Exec("UPDATE medications SET inventory_count = ? WHERE id = ?", count, medID)
	return err
}

// CreateRestock adds inventory and logs the restock event.
func (r *Repo) CreateRestock(medID int64, qty int, note string) error {
	tx, err := r.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	_, err = tx.Exec(`
		UPDATE medications
		SET inventory_count = COALESCE(inventory_count, 0) + ?
		WHERE id = ?`, qty, medID)
	if err != nil {
		return err
	}

	_, err = tx.Exec("INSERT INTO medication_restocks (medication_id, quantity, note) VALUES (?, ?, ?)", medID, qty, note)
	if err != nil {
		return err
	}

	return tx.Commit()
}

// ListRestocks returns restock events for a medication.
func (r *Repo) ListRestocks(medID int64) ([]Restock, error) {
	rows, err := r.db.Query("SELECT id, medication_id, quantity, note, restocked_at FROM medication_restocks WHERE medication_id = ? ORDER BY restocked_at DESC", medID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var restocks []Restock
	for rows.Next() {
		var rec Restock
		var note sql.NullString
		if err := rows.Scan(&rec.ID, &rec.MedicationID, &rec.Quantity, &note, &rec.RestockedAt); err != nil {
			return nil, err
		}
		if note.Valid {
			rec.Note = note.String
		}
		restocks = append(restocks, rec)
	}
	return restocks, nil
}

// ListLowOnStock returns medications with inventory tracking that
// are low on stock. daysThreshold: warn if stock lasts fewer than this many days.
func (r *Repo) ListLowOnStock(daysThreshold int) ([]Medication, error) {
	meds, err := r.List(false)
	if err != nil {
		return nil, err
	}

	var lowStock []Medication
	for _, m := range meds {
		if m.InventoryCount == nil {
			continue
		}

		dailyUsage := r.calculateDailyUsage(&m)
		if dailyUsage == 0 {
			continue
		}

		if r.hasEnoughStock(&m, dailyUsage, daysThreshold) {
			continue
		}

		lowStock = append(lowStock, m)
	}

	return lowStock, nil
}

// hasEnoughStock returns true if medication has enough stock. If medication
// has an end date, checks if stock lasts until end date; otherwise checks if
// stock lasts at least daysThreshold days.
func (r *Repo) hasEnoughStock(m *Medication, dailyUsage float64, daysThreshold int) bool {
	if m.InventoryCount == nil {
		return true
	}

	daysOfStock := float64(*m.InventoryCount) / dailyUsage

	if m.EndDate != nil {
		daysUntilEnd := time.Until(*m.EndDate).Hours() / 24
		if daysUntilEnd <= 0 {
			return true
		}
		return daysOfStock >= daysUntilEnd
	}

	return daysOfStock >= float64(daysThreshold)
}

// calculateDailyUsage returns the average daily intakes for a medication.
func (r *Repo) calculateDailyUsage(m *Medication) float64 {
	cfg, err := m.ValidSchedule()
	if err != nil {
		return 0
	}

	if cfg.Type == "as_needed" {
		return 0
	}

	timesPerDay := float64(len(cfg.Times))

	if cfg.Type == "daily" {
		return timesPerDay
	}

	if cfg.Type == "weekly" {
		daysPerWeek := float64(len(cfg.Days))
		return (daysPerWeek / 7.0) * timesPerDay
	}

	return 0
}

// GetDaysOfStockRemaining calculates how many days of stock remain for a medication.
func (r *Repo) GetDaysOfStockRemaining(m *Medication) *float64 {
	if m.InventoryCount == nil {
		return nil
	}

	dailyUsage := r.calculateDailyUsage(m)
	if dailyUsage == 0 {
		return nil
	}

	days := float64(*m.InventoryCount) / dailyUsage
	return &days
}

// IsLowOnStock checks if a medication is low on stock considering its end date.
func (r *Repo) IsLowOnStock(m *Medication, daysThreshold int) bool {
	if m.InventoryCount == nil {
		return false
	}

	dailyUsage := r.calculateDailyUsage(m)
	if dailyUsage == 0 {
		return false
	}

	return !r.hasEnoughStock(m, dailyUsage, daysThreshold)
}

// -- Intake Log --

// tzStepPlanStatusGate is the SQL predicate that limits action on
// source='tz_step' intake_log rows to those whose owning tz_transition_plan
// is in APPROVED or COMPLETED status. Centralized here so every read/write
// path that touches PENDING intakes applies the same gate.
//
// Why: DeletePendingPreMaterializedIntakesForPlan (the plan-cancel cleanup)
// is best-effort — if it fails after the plan-status UPDATE succeeds, the
// orphan PENDING tz_step rows would otherwise still fire reminders, be
// confirmed by stale Telegram/WebPush actions (decrementing inventory for a
// cancelled plan step), or appear in forecast / Take-next surfaces. The plan
// join makes all of that impossible by construction. Non-tz_step rows
// (source='schedule' and any future sources) bypass this gate.
//
// The predicate references the bare column `tz_plan_id` so it works in both
// SELECT WHERE and UPDATE WHERE clauses on intake_log (SQLite resolves
// unqualified columns to the target table).
const tzStepPlanStatusGate = `(
		source != 'tz_step'
		OR (
			tz_plan_id IS NOT NULL
			AND EXISTS (
				SELECT 1 FROM tz_transition_plans p
				WHERE p.id = intake_log.tz_plan_id
				  AND p.status IN ('APPROVED', 'COMPLETED')
			)
		)
	)`

// tzStepPlanStatusGateForDedup is a status-aware variant of
// tzStepPlanStatusGate used by the scheduler's dedup readers
// (BatchGetIntakesBySchedule, HasIntakeNearScheduledTime). It hides ONLY
// orphan PENDING source='tz_step' rows whose owning plan is not
// APPROVED/COMPLETED. Real TAKEN step rows survive plan cancel (see
// DeletePendingPreMaterializedIntakesForPlan — only PENDING rows are
// deleted) and represent doses the user actually consumed, so they must
// still suppress legitimate normal-schedule reminders for the same slot.
//
// Without this gate a best-effort delete failure on plan cancel would let
// an orphan PENDING tz_step row indefinitely hide the legitimate normal
// reminder for that slot. Without the status='TAKEN' exception we would
// double-fire normal reminders after the user took a step and then
// cancelled the plan.
const tzStepPlanStatusGateForDedup = `(
		source != 'tz_step'
		OR status != 'PENDING'
		OR (
			tz_plan_id IS NOT NULL
			AND EXISTS (
				SELECT 1 FROM tz_transition_plans p
				WHERE p.id = intake_log.tz_plan_id
				  AND p.status IN ('APPROVED', 'COMPLETED')
			)
		)
	)`

// scheduleNotShadowedByTZStepGate hides a PENDING source='schedule' row when a
// logically-active source='tz_step' sibling exists at the same
// (medication_id, scheduled_at_unix). The two rows represent the same logical
// dose (the scheduler fired the normal slot at T right before the user
// approved a plan whose snap-to-clock step also landed at T); without this
// gate the schedule row keeps firing MedicationReminderChecker reminders and
// is independently confirmable via confirm_intake / confirm_schedule, letting
// one dose decrement inventory twice and survive in history as a phantom.
//
// "Logically-active" mirrors tzStepPlanStatusGateForDedup applied to the
// sibling: a TAKEN/SKIPPED tz_step row, or a PENDING tz_step row whose plan is
// APPROVED/COMPLETED, suppresses the schedule row. Orphan PENDING tz_step
// rows from cancelled plans do NOT suppress — the schedule row is then the
// only actionable thing at that slot.
//
// Only applied to readers that drive user actions on PENDING rows
// (GetPendingIntakes, GetPendingIntakesBySchedule). History/forecast readers
// keep showing both rows so the user can still see what happened; the
// tz_step row wins their tie-break via ORDER BY.
const scheduleNotShadowedByTZStepGate = `(
		source != 'schedule'
		OR NOT EXISTS (
			SELECT 1 FROM intake_log step
			WHERE step.medication_id = intake_log.medication_id
			  AND step.scheduled_at_unix = intake_log.scheduled_at_unix
			  AND step.source = 'tz_step'
			  AND (
				step.status != 'PENDING'
				OR EXISTS (
					SELECT 1 FROM tz_transition_plans p
					WHERE p.id = step.tz_plan_id
					  AND p.status IN ('APPROVED', 'COMPLETED')
				)
			  )
		)
	)`

func (r *Repo) CreateIntake(medID, userID int64, scheduledAt time.Time) (int64, error) {
	res, err := r.db.Exec("INSERT INTO intake_log (medication_id, user_id, scheduled_at_unix, status) VALUES (?, ?, ?, 'PENDING')",
		medID, userID, scheduledAt.UTC().Unix())
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// LatestScheduledIntake returns the most-recent scheduled_at_unix for the
// given medication (zero time + found=false when the medication has no
// intake_log rows yet). Used by the demo top-up loop to resume per-medication
// dose generation from the last scheduled dose forward. intake_log has no
// UNIQUE constraint on (medication_id, scheduled_at_unix); the seeddemo
// top-up path enforces dedupe via a strict scheduledAt > latest guard.
func (r *Repo) LatestScheduledIntake(ctx context.Context, medID int64) (time.Time, bool, error) {
	var scheduledUnix sql.NullInt64
	if err := r.db.QueryRowContext(ctx,
		"SELECT MAX(scheduled_at_unix) FROM intake_log WHERE medication_id = ?", medID).Scan(&scheduledUnix); err != nil {
		return time.Time{}, false, err
	}
	if !scheduledUnix.Valid {
		return time.Time{}, false, nil
	}
	return time.Unix(scheduledUnix.Int64, 0).UTC(), true, nil
}

func (r *Repo) CreateManualIntake(medID, userID int64, takenAt time.Time) (int64, error) {
	// For manual intake, scheduled_at_unix = taken_at unix seconds.
	takenUnix := takenAt.UTC().Unix()
	res, err := r.db.Exec("INSERT INTO intake_log (medication_id, user_id, scheduled_at_unix, taken_at_unix, status) VALUES (?, ?, ?, ?, 'TAKEN')",
		medID, userID, takenUnix, takenUnix)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// ConfirmIntake marks a PENDING intake_log row as TAKEN. Defense in depth:
// tzStepPlanStatusGate hides orphan source='tz_step' rows whose owning plan
// was cancelled/rejected so a stale Telegram/WebPush callback cannot decrement
// inventory for a step the user already dismissed via the plan banner.
// Callers that hit the gate see sql.ErrNoRows just like a concurrent confirm,
// which the domain layer maps to ErrNotPending.
func (r *Repo) ConfirmIntake(id int64, takenAt time.Time) error {
	res, err := r.db.Exec(`
		UPDATE intake_log SET status = 'TAKEN', taken_at_unix = ?
		WHERE id = ? AND status = 'PENDING' AND `+tzStepPlanStatusGate,
		takenAt.UTC().Unix(), id)
	if err != nil {
		return err
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// SkipIntake marks a PENDING intake_log row as SKIPPED. Same orphan-tz_step
// gate as ConfirmIntake — see tzStepPlanStatusGate.
func (r *Repo) SkipIntake(id int64) error {
	res, err := r.db.Exec(`
		UPDATE intake_log SET status = 'SKIPPED', taken_at_unix = NULL
		WHERE id = ? AND status = 'PENDING' AND `+tzStepPlanStatusGate, id)
	if err != nil {
		return err
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// UpdateIntake mutates an intake_log row's status (and taken_at_unix when
// status='TAKEN'). The /api/intakes/update bulk handler verifies ownership
// then calls this — so an orphan PENDING source='tz_step' row from a
// CANCELLED plan surfaced through /api/history could otherwise be marked
// TAKEN here, bypassing the ConfirmIntake gate and decrementing inventory
// for a step the user already dismissed at the plan banner.
//
// The status-aware tzStepPlanStatusGateForDedup variant blocks ONLY orphan
// PENDING tz_step rows: a TAKEN tz_step row that survived plan cancellation
// (DeletePendingPreMaterializedIntakesForPlan only deletes PENDING rows) is
// still a real dose the user consumed, so /api/history corrections —
// revert to PENDING, retime the taken_at, switch to SKIPPED — must remain
// possible. Returns sql.ErrNoRows when the gate blocks the update; the
// handler observes that to skip the inventory adjustment that would
// otherwise run off the stale pre-read row state.
func (r *Repo) UpdateIntake(id int64, takenAt time.Time, status string) error {
	var takenAtUnixVal interface{}
	if status == "TAKEN" {
		takenAtUnixVal = takenAt.UTC().Unix()
	} else {
		takenAtUnixVal = nil
	}
	res, err := r.db.Exec(
		"UPDATE intake_log SET status = ?, taken_at_unix = ? WHERE id = ? AND "+tzStepPlanStatusGateForDedup,
		status, takenAtUnixVal, id)
	if err != nil {
		return err
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (r *Repo) SnoozeIntake(id int64, snoozeUntil time.Time) error {
	res, err := r.db.Exec("UPDATE intake_log SET snoozed_until_unix = ? WHERE id = ? AND status = 'PENDING'",
		snoozeUntil.UTC().Unix(), id)
	if err != nil {
		return err
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// ListPendingIntakes returns all PENDING intake_log rows that are
// user-actionable. The tzStepPlanStatusGate makes orphan source='tz_step'
// rows from cancelled/rejected plans invisible to every caller that flows
// through this reader (MedicationReminderChecker, ConfirmMedicationByMedID,
// etc.); see that constant for the threat model.
//
// scheduleNotShadowedByTZStepGate additionally hides a PENDING source='schedule'
// row when a logically-active source='tz_step' sibling exists at the same
// (medication_id, scheduled_at_unix). Without it, the normal scheduler firing
// the slot at T just before the user approves a plan whose snap-to-clock final
// step also lands at T would leave the schedule row PENDING after the user
// confirms the tz_step row — re-fired by MedicationReminderChecker and
// confirmable via confirm_intake / confirm:<medID> for a second inventory
// decrement on a single dose.
func (r *Repo) ListPendingIntakes() ([]IntakeLog, error) {
	rows, err := r.db.Query(`
		SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number
		FROM intake_log
		WHERE status = 'PENDING'
		  AND ` + tzStepPlanStatusGate + `
		  AND ` + scheduleNotShadowedByTZStepGate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	logs := []IntakeLog{}
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, nil
}

func (r *Repo) ListTakenIntakesBySchedule(userID int64, scheduledAt time.Time) ([]IntakeLog, error) {
	rows, err := r.db.Query("SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number FROM intake_log WHERE user_id = ? AND scheduled_at_unix = ? AND status = 'TAKEN'", userID, scheduledAt.UTC().Unix())
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	logs := []IntakeLog{}
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, nil
}

func (r *Repo) ListIntakeHistory(medID int, days int) ([]IntakeLog, error) {
	query := "SELECT id, medication_id, user_id, scheduled_at_unix, taken_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number FROM intake_log WHERE 1=1"
	args := []interface{}{}

	if medID > 0 {
		query += " AND medication_id = ?"
		args = append(args, medID)
	}

	if days > 0 {
		since := time.Now().Add(-time.Duration(days) * 24 * time.Hour)
		query += " AND scheduled_at_unix >= ?"
		args = append(args, since.UTC().Unix())
	}

	query += " ORDER BY scheduled_at_unix DESC LIMIT 100"

	rows, err := r.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	logs := []IntakeLog{}
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var takenUnix sql.NullInt64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &takenUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if takenUnix.Valid {
			t := time.Unix(takenUnix.Int64, 0).UTC()
			l.TakenAt = &t
		}
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, nil
}

func (r *Repo) GetIntake(id int64) (*IntakeLog, error) {
	var l IntakeLog
	var schedUnix int64
	var takenUnix sql.NullInt64
	var snoozeUnix sql.NullInt64
	var tzPlanID, tzStepNumber sql.NullInt64
	err := r.db.QueryRow("SELECT id, medication_id, user_id, scheduled_at_unix, taken_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number FROM intake_log WHERE id = ?", id).Scan(
		&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &takenUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
	if takenUnix.Valid {
		t := time.Unix(takenUnix.Int64, 0).UTC()
		l.TakenAt = &t
	}
	if snoozeUnix.Valid {
		t := time.Unix(snoozeUnix.Int64, 0).UTC()
		l.SnoozedUntil = &t
	}
	if tzPlanID.Valid {
		v := tzPlanID.Int64
		l.TZPlanID = &v
	}
	if tzStepNumber.Valid {
		v := tzStepNumber.Int64
		l.TZStepNumber = &v
	}
	return &l, nil
}

// GetIntakeBySchedule returns the intake_log row at (medID, scheduledAt) that
// is logically active. Orphan PENDING source='tz_step' rows whose owning plan
// is not APPROVED/COMPLETED are hidden via tzStepPlanStatusGateForDedup so
// callers that act on the result (Take-next, confirm-schedule, /next) don't
// pick up a zombie row that ConfirmIntake will then reject — when an orphan
// shares (medication_id, scheduled_at_unix) with a legitimate normal target
// the handler would otherwise see the orphan, fail to confirm it, and skip
// the slot entirely. TAKEN tz_step rows from any plan, and PENDING tz_step
// rows from APPROVED/COMPLETED plans, still pass through. Tests that need
// to introspect physical persistence of an orphan row must query intake_log
// directly.
//
// When a (medID, scheduledAt) slot has BOTH a source='schedule' row and a
// source='tz_step' row (e.g. the normal scheduler fired at T just before the
// user approved a plan whose final snap-to-clock step also landed at T), the
// tz_step row wins via the ORDER BY tiebreaker. Confirming the schedule row
// instead would leave the pre-materialized step PENDING — visible to the
// scheduler's fire path on the next tick — so prefer the plan-owned row.
func (r *Repo) GetIntakeBySchedule(medID int64, scheduledAt time.Time) (*IntakeLog, error) {
	var l IntakeLog
	var schedUnix int64
	var takenUnix sql.NullInt64
	var snoozeUnix sql.NullInt64
	var tzPlanID, tzStepNumber sql.NullInt64
	err := r.db.QueryRow(`SELECT id, medication_id, user_id, scheduled_at_unix, taken_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number
		FROM intake_log
		WHERE medication_id = ? AND scheduled_at_unix = ?
		  AND `+tzStepPlanStatusGateForDedup+`
		ORDER BY CASE WHEN source = 'tz_step' THEN 0 ELSE 1 END, id
		LIMIT 1`, medID, scheduledAt.UTC().Unix()).Scan(
		&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &takenUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
	if takenUnix.Valid {
		t := time.Unix(takenUnix.Int64, 0).UTC()
		l.TakenAt = &t
	}
	if snoozeUnix.Valid {
		t := time.Unix(snoozeUnix.Int64, 0).UTC()
		l.SnoozedUntil = &t
	}
	if tzPlanID.Valid {
		v := tzPlanID.Int64
		l.TZPlanID = &v
	}
	if tzStepNumber.Valid {
		v := tzStepNumber.Int64
		l.TZStepNumber = &v
	}
	return &l, nil
}

func (r *Repo) BatchGetIntakesBySchedule(schedules []MedicationSchedule) (map[MedicationSchedule]*IntakeLog, error) {
	result := make(map[MedicationSchedule]*IntakeLog, len(schedules))
	if len(schedules) == 0 {
		return result, nil
	}

	// SQLite maximum variables is typically 32766, but we'll use a conservative batch size.
	// Each tuple (medication_id, scheduled_at_unix) uses 2 variables.
	// 500 schedules * 2 = 1000 variables per batch.
	const batchSize = 500

	for i := 0; i < len(schedules); i += batchSize {
		end := i + batchSize
		if end > len(schedules) {
			end = len(schedules)
		}

		batch := schedules[i:end]
		placeholders := make([]string, len(batch))
		args := make([]interface{}, len(batch)*2)

		for j, sched := range batch {
			placeholders[j] = "(?, ?)"
			args[j*2] = sched.MedID
			args[j*2+1] = sched.ScheduledAt.UTC().Unix()
		}

		query := fmt.Sprintf(
			"SELECT id, medication_id, user_id, scheduled_at_unix, taken_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number FROM intake_log WHERE (medication_id, scheduled_at_unix) IN (%s) AND %s",
			strings.Join(placeholders, ", "),
			tzStepPlanStatusGateForDedup,
		)

		rows, err := r.db.Query(query, args...)
		if err != nil {
			return nil, err
		}

		for rows.Next() {
			var l IntakeLog
			var schedUnix int64
			var takenUnix sql.NullInt64
			var snoozeUnix sql.NullInt64
			var tzPlanID, tzStepNumber sql.NullInt64
			err := rows.Scan(
				&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &takenUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber,
			)
			if err != nil {
				rows.Close()
				return nil, err
			}
			l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
			if takenUnix.Valid {
				t := time.Unix(takenUnix.Int64, 0).UTC()
				l.TakenAt = &t
			}
			if snoozeUnix.Valid {
				t := time.Unix(snoozeUnix.Int64, 0).UTC()
				l.SnoozedUntil = &t
			}
			if tzPlanID.Valid {
				v := tzPlanID.Int64
				l.TZPlanID = &v
			}
			if tzStepNumber.Valid {
				v := tzStepNumber.Int64
				l.TZStepNumber = &v
			}
			// Key by UTC. Callers that look up with a non-UTC ScheduledAt
			// must convert via .UTC() — the scheduler dedupe path already does so.
			result[MedicationSchedule{MedID: l.MedicationID, ScheduledAt: l.ScheduledAt}] = &l
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		rows.Close()
	}

	return result, nil
}

// ConfirmIntakesBySchedule marks every PENDING intake whose scheduled_at_unix
// matches the supplied target as TAKEN, returning the IDs that were updated.
// The comparison is on the INTEGER scheduled_at_unix column, so it is
// independent of the caller's time.Location.
func (r *Repo) ConfirmIntakesBySchedule(userID int64, scheduledAt time.Time, takenAt time.Time) ([]int64, error) {
	candidates, err := r.ListPendingIntakesBySchedule(userID, scheduledAt)
	if err != nil {
		return nil, err
	}

	var ids []int64
	for _, c := range candidates {
		// ConfirmIntake guards on status='PENDING', so a concurrent confirm
		// returns sql.ErrNoRows here — treat that as "already taken" and skip
		// instead of failing the batch.
		if err := r.ConfirmIntake(c.ID, takenAt); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return nil, err
		}
		ids = append(ids, c.ID)
	}
	return ids, nil
}

func (r *Repo) CreateIntakeReminder(intakeID int64, messageID int) error {
	_, err := r.db.Exec("INSERT INTO intake_reminders (intake_id, message_id) VALUES (?, ?)", intakeID, messageID)
	return err
}

func (r *Repo) ListIntakeReminders(intakeID int64) ([]int, error) {
	rows, err := r.db.Query("SELECT message_id FROM intake_reminders WHERE intake_id = ?", intakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []int
	for rows.Next() {
		var id int
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, nil
}

func (r *Repo) BatchGetIntakeReminders(intakeIDs []int64) (map[int64][]int, error) {
	if len(intakeIDs) == 0 {
		return make(map[int64][]int), nil
	}

	result := make(map[int64][]int)

	chunkSize := 500
	for i := 0; i < len(intakeIDs); i += chunkSize {
		end := i + chunkSize
		if end > len(intakeIDs) {
			end = len(intakeIDs)
		}
		chunk := intakeIDs[i:end]

		args := make([]interface{}, len(chunk))
		placeholders := make([]string, len(chunk))
		for j, id := range chunk {
			args[j] = id
			placeholders[j] = "?"
		}

		query := fmt.Sprintf("SELECT intake_id, message_id FROM intake_reminders WHERE intake_id IN (%s)", strings.Join(placeholders, ","))
		rows, err := r.db.Query(query, args...)
		if err != nil {
			return nil, err
		}

		for rows.Next() {
			var intakeID int64
			var msgID int
			if err := rows.Scan(&intakeID, &msgID); err != nil {
				rows.Close()
				return nil, err
			}
			result[intakeID] = append(result[intakeID], msgID)
		}

		if err := rows.Err(); err != nil {
			rows.Close()
			return nil, err
		}
		rows.Close()
	}

	return result, nil
}

// ListPendingIntakesBySchedule returns every PENDING intake for the user whose
// scheduled_at_unix matches the supplied target instant. The match is on the
// INTEGER unix-seconds column, so it is independent of the caller's
// time.Location. Applies tzStepPlanStatusGate so the confirm_schedule:<unix>
// batch path cannot resurrect orphan tz_step rows from a cancelled plan.
//
// scheduleNotShadowedByTZStepGate additionally hides a PENDING source='schedule'
// row that has a logically-active source='tz_step' sibling at the same slot —
// without it, ConfirmIntakesBySchedule would confirm both rows of a dual-row
// collision and ConfirmScheduleWithCleanup would decrement inventory twice for
// the single dose those rows represent.
func (r *Repo) ListPendingIntakesBySchedule(userID int64, scheduledAt time.Time) ([]IntakeLog, error) {
	rows, err := r.db.Query(
		`SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number
		 FROM intake_log
		 WHERE user_id = ? AND status = 'PENDING'
		   AND scheduled_at_unix = ?
		   AND medication_id IN (SELECT id FROM medications WHERE archived = 0)
		   AND `+tzStepPlanStatusGate+`
		   AND `+scheduleNotShadowedByTZStepGate,
		userID, scheduledAt.UTC().Unix(),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var logs []IntakeLog
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return logs, nil
}

func (r *Repo) ListPendingIntakesForMedication(medID int64) ([]IntakeLog, error) {
	rows, err := r.db.Query("SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix, source, tz_plan_id, tz_step_number FROM intake_log WHERE medication_id = ? AND status = 'PENDING'", medID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var logs []IntakeLog
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, nil
}

func (r *Repo) DeleteIntake(id int64) error {
	_, err := r.db.Exec("DELETE FROM intake_log WHERE id = ?", id)
	return err
}

// ListIntakesSince returns every intake_log row (joined with its parent
// medication's name + dosage) whose scheduled_at_unix is >= the supplied
// instant. Used by the download / export endpoints.
func (r *Repo) ListIntakesSince(since time.Time) ([]IntakeWithMedication, error) {
	query := `
		SELECT
			il.id, il.medication_id, il.user_id, il.scheduled_at_unix, il.taken_at_unix, il.status, il.snoozed_until_unix,
			il.source, il.tz_plan_id, il.tz_step_number,
			m.name AS medication_name, m.dosage AS medication_dosage
		FROM intake_log il
		JOIN medications m ON il.medication_id = m.id
		WHERE il.scheduled_at_unix >= ?
		ORDER BY il.scheduled_at_unix DESC
	`
	rows, err := r.db.Query(query, since.UTC().Unix())
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var logs []IntakeWithMedication
	for rows.Next() {
		var l IntakeWithMedication
		var schedUnix int64
		var takenUnix sql.NullInt64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &takenUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber, &l.MedicationName, &l.MedicationDosage); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if takenUnix.Valid {
			t := time.Unix(takenUnix.Int64, 0).UTC()
			l.TakenAt = &t
		}
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, nil
}

// materializedStep is the minimal projection of tzreschedule.TransitionStep
// that MaterializePlanStepsAsIntakesTx needs in order to insert intake_log
// rows. The JSON keys mirror the PascalCase shape produced by
// `json.Marshal([]tzreschedule.TransitionStep)` in planner.go, so the same
// blob stored in tz_transition_plans.steps_json round-trips cleanly here.
type materializedStep struct {
	MedicationID int64     `json:"MedicationID"`
	StepNumber   int       `json:"StepNumber"`
	ScheduledAt  time.Time `json:"ScheduledAt"`
}

// MaterializePlanStepsAsIntakesTx reads the plan's steps_json blob and
// inserts one PENDING source='tz_step' row into intake_log per step. The
// insert uses INSERT OR IGNORE against the partial unique index added by
// migration 067, so re-running the materialize on the same plan (e.g. after a
// tx commit failure or a benign re-approve) is a no-op rather than a
// duplicate-key error.
//
// Track D Task 13 dropped the tz_transition_steps table; steps_json is now the
// single source of truth for "what doses does this plan introduce". The
// planner already serializes []tzreschedule.TransitionStep into that column at
// plan-create time, so this method does not need to touch any other table.
//
// Returns the number of rows actually inserted (zero on a re-run). Caller is
// responsible for the surrounding transaction (typically Repos.ApproveAndMaterialize).
func (r *Repo) MaterializePlanStepsAsIntakesTx(tx storedb.TX, planID, allowedUserID int64) (int64, error) {
	var stepsJSON string
	if err := tx.QueryRow(`SELECT steps_json FROM tz_transition_plans WHERE id = ?`, planID).Scan(&stepsJSON); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("materialize plan %d: load steps_json: %w", planID, err)
	}
	if stepsJSON == "" {
		return 0, nil
	}
	var steps []materializedStep
	if err := json.Unmarshal([]byte(stepsJSON), &steps); err != nil {
		return 0, fmt.Errorf("materialize plan %d: parse steps_json: %w", planID, err)
	}
	if len(steps) == 0 {
		return 0, nil
	}
	var total int64
	for _, s := range steps {
		if s.MedicationID == 0 || s.StepNumber == 0 {
			continue
		}
		res, err := tx.Exec(`
			INSERT OR IGNORE INTO intake_log
			  (medication_id, user_id, scheduled_at_unix, status,
			   source, tz_plan_id, tz_step_number)
			VALUES (?, ?, ?, 'PENDING', 'tz_step', ?, ?)`,
			s.MedicationID, allowedUserID, s.ScheduledAt.UTC().Unix(), planID, s.StepNumber)
		if err != nil {
			return total, fmt.Errorf("materialize plan %d step %d: %w", planID, s.StepNumber, err)
		}
		n, _ := res.RowsAffected()
		total += n
	}
	return total, nil
}

// DeletePendingPreMaterializedIntakesForPlan removes every PENDING intake_log
// row that was pre-materialized for the given plan (source='tz_step',
// tz_plan_id=planID). Rows the user has already confirmed (status='TAKEN')
// belong to the user even after a plan cancel, so they survive.
//
// Used by the planner's cancel path: when a plan is cancelled (superseded by a
// new tz change, rejected via the banner, etc.) the unfired step rows must be
// removed so the medication scheduler does not keep firing them.
func (r *Repo) DeletePendingPreMaterializedIntakesForPlan(planID int64) error {
	_, err := r.db.Exec(`
		DELETE FROM intake_log
		WHERE tz_plan_id = ? AND status = 'PENDING' AND source = 'tz_step'`, planID)
	return err
}

// GetDueTZStepIntakes returns every PENDING intake_log row with
// source='tz_step' whose scheduled_at_unix is at-or-before asOf and which
// has not yet been notified (no intake_reminders row references it). Used
// by MedicationChecker.Check to surface pre-materialized transition-plan
// step rows as fire-targets — see Task 11 of the scheduling-simplification
// plan (docs/plans/20260508-simplify-medication-scheduling-utc-and-pre-materialized-steps.md).
//
// The intake_reminders gate is what stops the medication scheduler from
// re-firing the same tz_step row on every 1-minute tick. Normal-schedule
// rows are deduped via "row already exists in intake_log" (BatchGet skips
// them after the first fire); tz_step rows already exist at approve time,
// so they need a separate gate. After the first fire AddIntakeReminder
// writes an intake_reminders row; subsequent ticks skip the intake here and
// MedicationReminderChecker takes over re-reminders via its snooze loop.
//
// Defense in depth: this also requires the owning tz_transition_plan to be
// in APPROVED or COMPLETED status. The plan-cancel path
// (DeletePendingPreMaterializedIntakesForPlan) is best-effort — if its
// DELETE fails after the plan-status UPDATE succeeds, leftover tz_step rows
// would otherwise fire here even though the plan was cancelled. The plan
// join makes that impossible by construction. COMPLETED is included because
// the scheduler may flip an APPROVED plan to COMPLETED earlier in the same
// tick (when no future PENDING steps remain) and we still want any
// past-but-unfired step rows to fire on this tick.
func (r *Repo) GetDueTZStepIntakes(asOf time.Time) ([]IntakeLog, error) {
	rows, err := r.db.Query(`
		SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix,
		       source, tz_plan_id, tz_step_number
		FROM intake_log
		WHERE status = 'PENDING' AND source = 'tz_step'
		  AND scheduled_at_unix <= ?
		  AND tz_plan_id IS NOT NULL
		  AND EXISTS (
		    SELECT 1 FROM tz_transition_plans p
		    WHERE p.id = intake_log.tz_plan_id
		      AND p.status IN ('APPROVED', 'COMPLETED')
		  )
		  AND NOT EXISTS (
		    SELECT 1 FROM intake_reminders r WHERE r.intake_id = intake_log.id
		  )`, asOf.UTC().Unix())
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var logs []IntakeLog
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, rows.Err()
}

// CountFuturePendingTZStepIntakesForPlan returns the number of PENDING
// intake_log rows for the given plan whose scheduled_at_unix is strictly
// after asOf. The medication scheduler uses this to mark an APPROVED plan
// COMPLETED once all of its pre-materialized step times have arrived (the
// pre-Track-D equivalent was "no remaining unconsumed tz_transition_steps").
func (r *Repo) CountFuturePendingTZStepIntakesForPlan(planID int64, asOf time.Time) (int, error) {
	var n int
	err := r.db.QueryRow(`
		SELECT COUNT(*) FROM intake_log
		WHERE tz_plan_id = ? AND source = 'tz_step'
		  AND status = 'PENDING'
		  AND scheduled_at_unix > ?`, planID, asOf.UTC().Unix()).Scan(&n)
	return n, err
}

// MedsWithFuturePendingTZStepsForPlan returns the distinct medication IDs
// that still have at least one PENDING source='tz_step' row in intake_log
// with scheduled_at_unix > asOf for the given plan. The medication scheduler
// uses this to skip normal-schedule emission for those meds while an
// APPROVED plan still has steps to fire, restoring the pre-Track-D
// "plan owns this med while steps remain" suppression. Without it the
// symmetric ±minInterval dedup (HasIntakeNearScheduledTime) only covers
// targets within minInterval of an existing step row; a normal slot that
// falls in a gap > 2*minInterval between consecutive steps would otherwise
// fire mid-transition.
func (r *Repo) MedsWithFuturePendingTZStepsForPlan(planID int64, asOf time.Time) ([]int64, error) {
	rows, err := r.db.Query(`
		SELECT DISTINCT medication_id FROM intake_log
		WHERE tz_plan_id = ? AND source = 'tz_step'
		  AND status = 'PENDING'
		  AND scheduled_at_unix > ?`, planID, asOf.UTC().Unix())
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// HasIntakeNearScheduledTime reports whether an intake_log row for the given
// medication exists within ±window of target, with status in
// ('PENDING', 'TAKEN'). The scheduler uses this as the symmetric
// ±minInterval dedup replacement for medplan's removed consumed-step
// overlap guard — see Task 11 of the scheduling-simplification plan.
func (r *Repo) HasIntakeNearScheduledTime(medID int64, target time.Time, window time.Duration) (bool, error) {
	if window < 0 {
		window = -window
	}
	targetUnix := target.UTC().Unix()
	windowSec := int64(window / time.Second)
	var n int
	err := r.db.QueryRow(`
		SELECT COUNT(*) FROM intake_log
		WHERE medication_id = ?
		  AND status IN ('PENDING', 'TAKEN')
		  AND scheduled_at_unix BETWEEN ? AND ?
		  AND `+tzStepPlanStatusGateForDedup+`
		LIMIT 1`, medID, targetUnix-windowSec, targetUnix+windowSec).Scan(&n)
	if err != nil {
		return false, err
	}
	return n > 0, nil
}

// GetPendingIntakesInWindow returns every PENDING intake_log row whose
// scheduled_at_unix lies in (start, end]. Used by the next-intake forecast
// endpoints to surface pre-materialized tz_step rows (and any other PENDING
// rows) alongside medplan's normal-schedule targets — see Task 12 of
// docs/plans/20260508-simplify-medication-scheduling-utc-and-pre-materialized-steps.md.
// The window matches medplan's forecast-mode predicate so the two sources
// dedup cleanly on (medication_id, scheduled_at_unix).
//
// Defense in depth: source='tz_step' rows are only returned when their owning
// tz_transition_plan is in APPROVED or COMPLETED status — mirroring the gate
// in GetDueTZStepIntakes. The plan-cancel path
// (DeletePendingPreMaterializedIntakesForPlan) is best-effort, so a leftover
// PENDING tz_step row could otherwise appear in the forecast / Take-next
// surfaces (via suppressNormalsCoveredByStep it would also hide the normal
// target for that med) even after the user dismissed the plan. Non-tz_step
// rows (source='schedule' and any future sources) bypass this gate and are
// always returned when PENDING.
//
// Rows are ordered so that source='tz_step' rows appear first at any
// (medication_id, scheduled_at_unix). The forecast/Take-next dedup
// (medication_handlers.go / settings_handlers.go) keeps the first row it sees
// at each key, then suppressNormalsCoveredByStep drops any remaining
// SourceNormalSchedule entry for plan-owned meds. Without the ordering a
// pre-existing source='schedule' row at the same instant as a materialized
// step would win the dedup, get marked SourceNormalSchedule, and then be
// dropped by the plan-owned suppression — silently hiding the dose. The
// schedule row can co-exist if the normal scheduler fired at T just before
// the user approved a plan whose snap-to-clock final step also landed at T.
func (r *Repo) GetPendingIntakesInWindow(start, end time.Time) ([]IntakeLog, error) {
	rows, err := r.db.Query(`
		SELECT id, medication_id, user_id, scheduled_at_unix, status, snoozed_until_unix,
		       source, tz_plan_id, tz_step_number
		FROM intake_log
		WHERE status = 'PENDING'
		  AND scheduled_at_unix > ? AND scheduled_at_unix <= ?
		  AND `+tzStepPlanStatusGate+`
		ORDER BY scheduled_at_unix, medication_id,
		         CASE WHEN source = 'tz_step' THEN 0 ELSE 1 END,
		         id`,
		start.UTC().Unix(), end.UTC().Unix())
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var logs []IntakeLog
	for rows.Next() {
		var l IntakeLog
		var schedUnix int64
		var snoozeUnix sql.NullInt64
		var tzPlanID, tzStepNumber sql.NullInt64
		if err := rows.Scan(&l.ID, &l.MedicationID, &l.UserID, &schedUnix, &l.Status, &snoozeUnix, &l.Source, &tzPlanID, &tzStepNumber); err != nil {
			return nil, err
		}
		l.ScheduledAt = time.Unix(schedUnix, 0).UTC()
		if snoozeUnix.Valid {
			t := time.Unix(snoozeUnix.Int64, 0).UTC()
			l.SnoozedUntil = &t
		}
		if tzPlanID.Valid {
			v := tzPlanID.Int64
			l.TZPlanID = &v
		}
		if tzStepNumber.Valid {
			v := tzStepNumber.Int64
			l.TZStepNumber = &v
		}
		logs = append(logs, l)
	}
	return logs, rows.Err()
}
