#!/bin/sh
# Copy capacitor/android-overlay/ on top of capacitor/android/.
#
# capacitor/android/ is generated by `npx cap add android` and gitignored,
# so files we add to it (custom MainActivity, gradle snippets, jniLibs) get
# blown away on a fresh checkout. This script re-applies our overlay tree
# after `cap add android` so the build is reproducible.
#
# Idempotent — re-running just overwrites. Pre-existing files in
# android/ that are NOT in android-overlay/ are left untouched.
#
# Usage:
#   cd capacitor
#   ./apply-overlay.sh
#
# Or from the repo root:
#   ./capacitor/apply-overlay.sh
#
# Build the binaries BEFORE running this — the overlay's jniLibs/<abi>/
# files only exist after scripts/build-android-binaries.sh has populated them.

set -eu

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
OVERLAY_DIR="${SCRIPT_DIR}/android-overlay"
ANDROID_DIR="${SCRIPT_DIR}/android"

if [ ! -d "$ANDROID_DIR" ]; then
  printf 'error: %s does not exist. Run "npx cap add android" first.\n' "$ANDROID_DIR" >&2
  exit 1
fi

if [ ! -d "$OVERLAY_DIR" ]; then
  printf 'error: overlay directory missing at %s\n' "$OVERLAY_DIR" >&2
  exit 1
fi

# Build a sentinel file list so we can skip the no-op cases cleanly. `find`
# excludes the overlay's own meta files that we don't want to copy.
SENTINELS="README.md .gitignore .gitkeep"

copied=0
while IFS= read -r src; do
  rel=${src#"$OVERLAY_DIR/"}
  base=$(basename "$rel")

  skip=0
  for s in $SENTINELS; do
    if [ "$base" = "$s" ]; then
      skip=1
      break
    fi
  done
  if [ "$skip" -eq 1 ]; then
    continue
  fi

  dst="${ANDROID_DIR}/${rel}"
  dst_dir=$(dirname "$dst")
  mkdir -p "$dst_dir"
  cp "$src" "$dst"
  printf '  %s\n' "$rel"
  copied=$((copied + 1))
done <<EOF
$(find "$OVERLAY_DIR" -type f)
EOF

if [ "$copied" -eq 0 ]; then
  printf 'No overlay files found. Did you run scripts/build-android-binaries.sh first?\n' >&2
  exit 0
fi

printf '\nApplied %d file(s) from android-overlay/ to android/.\n' "$copied"

# build.gradle reminder. medtracker.build.gradle ships in the overlay so it gets
# copied into android/app/, but Capacitor's app/build.gradle won't `apply from`
# it until we add a one-line stanza. Detect-and-warn rather than auto-edit:
# touching the generated build.gradle would surprise future `cap add` runs.
APP_BUILD_GRADLE="${ANDROID_DIR}/app/build.gradle"
APPLY_LINE="apply from: 'medtracker.build.gradle'"
if [ -f "$APP_BUILD_GRADLE" ]; then
  if ! grep -qF "$APPLY_LINE" "$APP_BUILD_GRADLE"; then
    printf '\nReminder: append the following line to %s\n' "$APP_BUILD_GRADLE"
    printf '         (one-time edit; survives subsequent overlay runs):\n\n'
    printf '    %s\n\n' "$APPLY_LINE"
    printf 'This pulls in androidx.security:security-crypto + okhttp + coroutines\n'
    printf 'required by MainActivity.kt and GoServerService.kt.\n'
  fi
fi
