name: Release Installer

on:
  push:
    tags:
      - "installer-v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This ensures all tags are fetched

      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/installer/go.mod
          cache-dependency-path: cmd/installer/go.sum

      - name: Clean Tag
        run: |
          # Takes 'installer-v0.1.1' and turns it into 'v0.1.1'
          CLEAN_TAG=${GITHUB_REF_NAME#installer-}
          echo "GORELEASER_CURRENT_TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --skip=validate
          workdir: cmd/installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.GORELEASER_CURRENT_TAG }}
